### PR TITLE
chunked buffer

### PR DESCRIPTION
**Pull request by WilliamSmith21**
added test class for chunked buffer

### CODE REVIEW

**Comment by WilliamSmith21** [comment]
hey @krishpranav I have added chunked buffer test class both hpp & cpp added pls take a look at it 😄

**Comment by krishpranav** [comment]
thanks let me check it

**Comment by WilliamSmith21** [comment]
ok sure @krishpranav

**Comment by krishpranav** [comment]
great work @WilliamSmith21

**Comment by WilliamSmith21** [comment]
thank you 😸

**Comment by krishpranav** [comment]
__MERGED__

**Comment by WilliamSmith21** [comment]
👍

**Pull request merged**
